name: Run Spectral on Pull Requests

on:
  - pull_request
  - push

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.8.0
        with:
          file_glob: './fixtures/*.yml'
          spectral_ruleset: .my-custom.spectral.yml
        continue-on-error: true

      - if: steps.expect-failure.output.status == 'failure'
        run: exit 0
